app:
  jwt:
    secrete: GawaniJusticeKasawala
    expiration: 2000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 10000
      max-lifetime: 40000
      auto-commit: true
    username: postgres
    password: Jexy@2021
  main:
    banner-mode: off
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view:  false
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: always
  flyway:
    enabled: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: on_param
  tomcat:
    connection-timeout: 70000
  port: 8082

